on:
  push:
    branches:
      - main
      - use-image-cache # TODO for test REMOVE ME.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/yskszk63/cdk-template
          cacheFrom: ghcr.io/yskszk63/cdk-template
          push: always
